event:
  name: 2020_boogaloo_CA
  state: CA
  input_file: data/event_data/raw/2020_boogaloo_CA.csv
  start_date: 2020-05-22
  end_date: 2020-07-06
  onset_date: 2020-05-29
  keywords: [boogaloo, extremism, militia, shootings, terrorism, armed, supremacist, attack, violence, arrests]
