event:
  name: 2022_massshooting_NY
  state: NY
  input_file: data/event_data/raw/2022_massshooting_NY.csv
  start_date: 2022-05-07
  end_date: 2022-06-14
  onset_date: 2022-05-14
  keywords: [mass shooting, gunman, victims, white supremacist, supermarket, racism, terrorism, hate, fatalities, gun violence]
  hatespeech_keywords: [white supremacist, racist, antisemitic, hate crime, extremist, bigotry]
  misinformation_keywords: [false flag, hoax, staged attack, conspiracy, propaganda, coverup]
  policy_keywords: [domestic terrorism, hate crime law, gun control, law enforcement, homeland security, prosecution]
