event:
  name: 2022_massshooting_NY
  state: NY
  input_file: data/event_data/raw/2022_massshooting_NY.csv
  start_date: 2022-05-07
  end_date: 2022-06-14
  onset_date: 2022-05-14
  keywords: [mass shooting, gunman, victims, white supremacist, supermarket, racism, terrorism, hate, fatalities, gun violence]
