event:
  name: 2019_elpaso_tx
  state: TX
  input_file: data/event_data/raw/2019_elpaso_tx.csv
  start_date: 2019-07-26
  end_date: 2019-09-03
  onset_date: 2019-08-03
  keywords: [mass shooting, walmart, gunman, victims, terrorism, shooting, hate, racism, fatalities, gun violence]
  hatespeech_keywords: [white supremacist, racist, antisemitic, xenophobic, hate crime, extremist, bigotry, radicalization, dehumanization, violence]
  misinformation_keywords: [false flag, hoax, staged attack, conspiracy, propaganda, coverup, crisis actors, psyop, manipulation, disinformation]
  policy_keywords: [domestic terrorism, hate crime law, gun control, law enforcement, homeland security, prosecution, extremism, public safety, investigation, accountability]
