event:
  name: 2023_monterey_ca
  state: CA
  input_file: data/event_data/raw/2023_monterey_ca.csv
  start_date: 2023-01-14
  end_date: 2023-02-21
  onset_date: 2023-01-21
  keywords: [mass shooting, gunman, victims, lunar, gun, celebration, gun violence, kill, shooting, fatalities]
