event:
  name: 2025_fires_CA
  state: CA
  input_file: ../data/event_data/2025_fires_CA.csv
  start_date: 2025-01-01
  end_date: 2025-02-01
  keywords: [wildfire, fire, california, evacuation, smoke, emergency, homes, damage, response, disaster]
