event:
  name: 2021_tornado_KY
  state: KY
  input_file: data/event_data/raw/2021_tornado_KY.csv
  start_date: 2021-12-03
  end_date: 2022-02-10
  onset_date: 2021-12-10
  keywords: [tornado, storms, destruction, homes, fatalities, emergency, rescue, evacuation, damage, disaster]
  hatespeech_keywords: [government failure, neglect, incompetence, blame, corruption, betrayal, outrage, injustice, anger, resentment]
  misinformation_keywords: [storm hoax, fake tornado, weather manipulation, cloud seeding, coverup, conspiracy, propaganda, exaggeration, hoax, disinformation]
  policy_keywords: [disaster declaration, emergency response, fema, evacuation orders, infrastructure, storm preparedness, public safety, recovery, relief funding, climate policy]