event:
  name: 2022_uvalde_tx
  state: TX
  input_file: data/event_data/raw/2022_uvalde_tx.csv
  start_date: 2022-05-17
  end_date: 2022-06-24
  keywords: [shooting, school, gunman, victims, children, police, uvalde]
