event:
  name: 2019_vabeach_VA
  state: VA
  input_file: data/event_data/raw/2019_vabeach_VA.csv
  start_date: 2019-05-24
  end_date: 2019-06-30
  onset_date: 2019-05-31
  keywords: [shooting, gunman, victims, workplace, police, kill, virginia, beach, fatalities, attack]
